### ISSUE TITLE
Fix environment issues

### ISSUE THREAD

**Issue by user2745** [protest-location-pinger/app#32]
- [x] Remove docker dependency
- [x] Implement MongoDB
- [x] Remove MySQL dependency

**Comment by dgatto** [comment]
https://stackoverflow.com/questions/50093144/mysql-8-0-client-does-not-support-authentication-protocol-requested-by-server/52175673

**Comment by dgatto** [comment]
based on: https://github.com/polcham/mongoose-express-ts
