### ISSUE TITLE
Structure API with Proper Architecture

### ISSUE THREAD

**Issue by dgatto** [protest-location-pinger/app#4]
There's many ways to architect an Express app, [heres one way to do so](https://softwareontheroad.com/ideal-nodejs-project-structure/).

That article explains a lot of important principals that help with the motivations behind how Express apps are architected.

It’s possible that #2 and #7 may overlap with this.

**Comment by user2745** [comment]
+1 thanks for adding the article link

**Comment by dgatto** [comment]
Used [this resource](https://github.com/polcham/mongoose-express-ts) for the refactor.
