### ISSUE TITLE
Investigate accessibility needs

### ISSUE THREAD

**Issue by dgatto** [protest-location-pinger/app#97]
https://www.nngroup.com/

Good resource for accessibility/usability paradigms.

https://www.nngroup.com/videos/dont-listen-to-customers/

**Comment by Hermesthe** [comment]
https://material.io/design/usability/accessibility.html#hierarchy (best practices)
https://developer.android.com/guide/topics/ui/accessibility/apps (some examples)
https://developer.android.com/guide/topics/ui/accessibility/apps <accessibility testing apps>
